### ISSUE TITLE
After Installing Warning

### ISSUE THREAD

**Issue by carlocarlini** [kolbasa/cordova-plugin-apkupdater#15]
After installation a message is asking if to quit or Open the App, but choosing **Open** is not producing any action.

**Comment by kolbasa** [comment]
On which device(emulator?), with which Android version does this happen?

**Comment by carlocarlini** [comment]
- Xiaomi 10 lite 
- and Samsung J5 Prime

**Comment by kolbasa** [comment]
Android Versions?

**Comment by kolbasa** [comment]
And this also happens with the Samsung device?

**Comment by carlocarlini** [comment]
WIth Samsung the screen of the installation overlaps the screen of the App and the message is not even shown. The App just quits

**Comment by kolbasa** [comment]
Ok, thanks for the tip. I'll see what I can do. 
I'll definitely have to check that out. :+1:

**Comment by carlocarlini** [comment]
thanks to you, i will be glad to test on my devices

**Comment by kolbasa** [comment]
So far, I have not been able to reproduce the behavior here. I also fear that there is nothing I can do here. The actual installation is managed by Android.
However, the update should still install in that case. Only the restart of the app fails.

**Comment by kolbasa** [comment]
The issue is reopened. I can reproduce it now after all and am already working on a solution.

Here you can see some progress. The plugin can skip the dialog completely and start the app without having to press "Open".

![Dialog](https://user-images.githubusercontent.com/3901582/120114308-dea00080-c17e-11eb-96b6-ece1baac76aa.gif)

**Comment by carlocarlini** [comment]
Hi
is it already possible to test the update?

**Comment by kolbasa** [comment]
No, not yet. For this to work a permission must be requested from the user (MANAGE_OVERLAY_PERMISSION). 
For the example I have set the permission manually.
So I still need to build the function to request it. I need one more day.

**Comment by kolbasa** [comment]
Okay, I'm an idiot. I've been looking for a way to trick Android for hours now. And now I realize that it was just a little bug in my installation logic. 
The bug is now fixed on the `master` branch and can already be tested with the [demo](https://github.com/kolbasa/cordova-plugin-apkupdater-demo).
I will create a release version soon.

**Comment by carlocarlini** [comment]
if you are an idiot i'd like to be idiot too...
i'm looking forward to test the update of the updater ;)

**Comment by kolbasa** [comment]
See release: `1.2.4`. You are welcome to reopen the issue if it still doesn't work.
