### ISSUE TITLE
Set device owner for Android TV

### ISSUE THREAD

**Issue by software-OSG** [kolbasa/cordova-plugin-apkupdater#38]
Hello,

Is it possible to set device owner for Android TV devices?
`adb shell dpm set-device-owner` works with Android tablets and phones but not Android TV boxes?
Error:
`...RuntimeException: Can't set package my.app.id as device owner...`

**Comment by kolbasa** [comment]
Good question. I didn't think there was a difference.
The [first Google search](https://stackoverflow.com/questions/47977467/device-owner-on-android-tv-box-not-working) suggests that this is not possible.

I'll try this out and report back later.

**Comment by software-OSG** [comment]
Thank you @kolbasa

**Comment by kolbasa** [comment]
I have now tested it in the emulator:
`Android TV - x86 - API 31`

It worked for me without any problems.

Here are my steps:

1. Download my [demo](https://github.com/kolbasa/cordova-plugin-apkupdater-demo)
2. Install demo app with: `adb install Demo.apk`
3. Start demo app with: `adb shell am start -n de.kolbasa.apkupdater.demo/de.kolbasa.apkupdater.demo.MainActivity`
4. Set device owner: `adb shell dpm set-device-owner de.kolbasa.apkupdater.demo/de.kolbasa.apkupdater.tools.DAReceiver`
5. The button `isDeviceOwner()` returns `true`.

Otherwise, I think I need more details. Which device, which version do you use? Did you replace the app id correctly in the `dpm set-device-owner` command?
